
package web.service.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://service.service.web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuroToDn")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuroToDn", targetNamespace = "http://service.service.web/", className = "web.service.service.ConversionEuroToDn")
    @ResponseWrapper(localName = "ConversionEuroToDnResponse", targetNamespace = "http://service.service.web/", className = "web.service.service.ConversionEuroToDnResponse")
    @Action(input = "http://service.service.web/BanqueWS/ConversionEuroToDnRequest", output = "http://service.service.web/BanqueWS/ConversionEuroToDnResponse")
    public double conversionEuroToDn(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<web.service.service.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://service.service.web/", className = "web.service.service.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://service.service.web/", className = "web.service.service.GetComptesResponse")
    @Action(input = "http://service.service.web/BanqueWS/getComptesRequest", output = "http://service.service.web/BanqueWS/getComptesResponse")
    public List<Compte> getComptes();

    /**
     * 
     * @param code
     * @return
     *     returns web.service.service.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://service.service.web/", className = "web.service.service.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://service.service.web/", className = "web.service.service.GetCompteResponse")
    @Action(input = "http://service.service.web/BanqueWS/getCompteRequest", output = "http://service.service.web/BanqueWS/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

}
